// layout.js หรือ RootLayout.js
import { Prompt } from 'next/font/google';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const prompt = Prompt({
  subsets: ['thai', 'latin'],
  weight: ['400', '500', '600'],
  variable: '--font-prompt',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={`${geistSans.variable} ${geistMono.variable} ${prompt.variable}`}>
        {children}
      </body>
    </html>
  );
}